"""The Sep30 package had proven music that build_post omitted. All checks are offline."""
import copy
import json
import sys
from pathlib import Path

import pytest

TOOLS = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(TOOLS))
import manifest as mf

MUSIC = json.loads((Path(__file__).parent / "fixtures/vsco-music.json").read_text(encoding="utf-8"))
REAL = TOOLS.parent / "v/2026-09-30/manifest.json"


def real_manifest():
    return json.loads(REAL.read_text(encoding="utf-8"))


def package_and_spec(tmp_path):
    m = real_manifest()
    p = next(p for p in m["posts"] if p["slot"] == 4)
    platforms = p["platforms"]
    package = {
        "x": {"post": platforms["x"]["text"], "reply": platforms["x"]["reply"]},
        "instagram": {"caption": platforms["instagram"]["caption"], "first_comment": platforms["instagram"]["first_comment"]},
        "threads": {"post": platforms["threads"]["text"], "first_reply": platforms["threads"]["first_reply"]},
        "pinterest": {k: platforms["pinterest"][k] for k in ("title", "description", "link")},
        "alt_text": p["alt_text"], "source_urls": p["source_urls"],
    }
    repo = tmp_path / "repo"
    directory = repo / "v/2026-09-30" / p["story_id"]
    directory.mkdir(parents=True)
    for fmt in mf.FORMATS:
        (directory / f"{fmt}.mp4").write_bytes(b"test-only media")
    pkg_path = tmp_path / "package.json"
    spec = {k: p[k] for k in ("slot", "time_et", "category", "story_id", "story_key", "title", "tickers", "people")}
    spec["post_package"] = str(pkg_path)
    return package, pkg_path, spec, repo


def test_captured_vsco_package_block_survives_writer_unchanged(tmp_path):
    package, path, spec, repo = package_and_spec(tmp_path)
    package["music"] = MUSIC
    path.write_text(json.dumps(package), encoding="utf-8")
    post = mf.build_post("2026-09-30", spec, "feed", repo)
    assert post["music"] == MUSIC
    m = real_manifest()
    m["posts"] = [post]
    assert mf.validate_manifest(m, "2026-09-30") == []


@pytest.mark.parametrize("legacy_null", [False, True])
def test_legacy_missing_or_null_package_never_invents_music(tmp_path, legacy_null):
    package, path, spec, repo = package_and_spec(tmp_path)
    if legacy_null:
        package["music"] = None
    path.write_text(json.dumps(package), encoding="utf-8")
    assert "music" not in mf.build_post("2026-09-30", spec, "feed", repo)


def test_real_synthesis_variant_and_legacy_absence_remain_valid():
    m = real_manifest()
    assert mf.validate_manifest(m) == []
    m["posts"][1]["music"] = {"type": "original score", "samples": None,
        "synthesis": "numpy/scipy, generated by RapidTradeView (scripts/score_v6.py)", "third_party_tracks": False}
    assert mf.validate_manifest(m) == []


@pytest.mark.parametrize("change", [
    lambda m: m.update(type="unverified rights"),
    lambda m: m.update(third_party_tracks=True),
    lambda m: m.update(third_party_tracks=0),
    lambda m: m.update(samples=""),
    lambda m: m.update(version="x" * 201),
    lambda m: m.update(license="x" * 121),
    lambda m: m.update(credit="x" * 501),
    lambda m: m.update(synthesis="x" * 301),
    lambda m: m.update(license_url="http://example.com/license"),
    lambda m: m.update(source_url="https://example.com/ bad"),
    lambda m: m.update(source_url="https://example.com/\u200b"),
    lambda m: m.update(source_url="https://example.com/" + "\U0001f600" * 250),
    lambda m: m.update(archive_sha256="bad-hash"),
    lambda m: m.update(credit="#insidertrading"),
    lambda m: m.update(unknown_claim=True),
    lambda m: m.pop("license"),
])
def test_malformed_music_is_rejected_before_publication(change):
    music = copy.deepcopy(MUSIC)
    change(music)
    m = real_manifest()
    m["posts"][1]["music"] = music
    assert any("music" in e for e in mf.validate_manifest(m))


@pytest.mark.parametrize("invalid", [None, False, [], {}])
def test_explicit_invalid_public_music_is_not_a_rights_claim(invalid):
    m = real_manifest()
    m["posts"][1]["music"] = invalid
    assert any("music" in e for e in mf.validate_manifest(m))


def test_synthesis_cannot_omit_description_or_smuggle_bad_optional_provenance():
    m = real_manifest()
    p = m["posts"][1]
    p["music"] = {"type": "original score", "samples": None, "third_party_tracks": False}
    assert any("synthesis" in e for e in mf.validate_manifest(m))
    p["music"]["synthesis"] = "numpy/scipy, generated by RapidTradeView (scripts/score_v6.py)"
    p["music"]["source_url"] = "http://example.com"
    assert any("source_url" in e for e in mf.validate_manifest(m))
